### ISSUE TITLE
Add a Jerk-Limited Trajectory Generator Because Box test is too aggressive

### ISSUE THREAD

**Issue by murphym18** [DroneResponse/hardware-tests#16]
The box test worked but its motion is too aggressive. We need to limit acceleration, velocity, and other rough behaviors. Otherwise offboard mode is scary.

In off board mode, the drone flies with the full responsiveness allowed to pilots. So it can stop on a dime, and accelerate VERY quickly (when descending it looks like it's falling from the sky). This degree of responsiveness exists so that pilots have the best chance of avoiding any problems.

However, an automated mode should fly in a more measured manner. That way, a human pilot has enough time to see what's going on and react, if needed. Only in emergency circumstances is it acceptable for the drone to fly so aggressively in an automated mode. 

Position mode and mission mode use special settings and parameters to limit jerky or fast motion. These limits make it easier for a pilot to take over. These modes limit:
- jerk (3rd time derivative of position)
- acceleration (both vertical and horizontal)
- bank angles
- Rate Limits
- angular acceleration
- max velocity

The specific values assigned for these limits are tuned for the aircraft and its payload.

The software must read the relevant parameters and adjust the set-point animation accordingly.

**Comment by murphym18** [comment]
Right now, my approach is to create a function, `s(t)`, that returns the position setpoint of the drone in 1 dimention, given `t` the time (in seconds) since we started the maneuver.

To make the calculation easier, we only need to consider the motion in 1 dimension. We're moving in a straight line and we need the function to tell us where we are along the line. The starting position is at 0. The final position is at the distance to our target. We have a way of calculating the latitude, longitude, and altitude given this distance along the path. For example, if our target position is 25 meters away:
- `s(0) = 0`
- `s(t_final) = 25`
- `s(t_final + x) = 25` for all `x > 0`

With `s(t)` here's how we can find the setpoint that we send to the drone:
1. let `start_position` be the place where the drone is when the maneuver starts (this is a latitude, longitude, altitude value where altitude is ellipsoidal)
2. let `target_position` be the place we want to reach (this is a latitude, longitude, altitude value where altitude is ellipsoidal)
3. find the ECEF coordinates of `start_position` and `target_position`. Lets call them `start_ecef` and `target_ecef`
4. find the vector that points from `start_ecef` to `target_ecef`, that is `delta_pos = target_ecef - start_ecef`
5. find the unit vector that points in the same direction as `delta_pos` and call it `delta_pos_hat`
6. find the ECEF coordinate of the next setpoint using `setpoint_ecef = start_ecef + delta_pos_hat * s(t)`
7. find the LLA of `setpoint_ecef`, call it `setpoint_lla_ellipsoid`
8. find the latitude longitude and altitude above sea level of `setpoint_lla_ellipsoid` and call it `setpoint_lla_amsl`
9. update the active setpoint to `setpoint_lla_amsl`

With all that in mind, this problem boils down to finding `s(t)` and it seems like we need to build everything starting from jerk. There is a PX4 parameter that tells us what jerk value to use. It's called [MPC_JERK_AUTO](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_JERK_AUTO). By default this value is 4 m/s^3. Practically speaking, we can have three possible jerk values at any given time: `+MPC_JERK_AUTO`, 0, and `-MPC_JERK_AUTO`(or 4, 0, and -4 by default).

From there we need to determine our acceleration limit. I didn't see a parameter about acceleration, but I did see values related to thrust limits. It looks like PX4 operates with thrust limits instead of acceleration limits. To go from thrust to acceleration we can use `F = Ma` to end up with `a = F/M` where F is the thrust limit, M is the mass of the drone and a is the acceleration limit. This changes depending on our payload. For now, I'm going to use a constant value: of 2 m/s^2 because that's an easy number and it about `20% * g` where "little g" is 9.8 m/s^2 (the standard acceleration due to Earth's gravity). This means acceleration will be limited to 20% of freefall acceleration. We can change this later but I want to start with a value that is clearly slower than freefall.

Next we need to pick our velocity limit. This is the speed we want to fly at. I think 5 m/s is a good example value. But we can pick whatever we want. 

And for our position limit, 25 meters seems like a good example value. This is the distance from the starting position to the destination.

**Comment by murphym18** [comment]
This example is inspired by the first maneuver in the box test. In this maneuver we fly 25 meters west and 3 meters up. But for now, I'm going to ignore the change in altitude. So we're only flying 25 meters west.

Given:
jerk limit = 4 m/s^3
acceleration limit = 2 m/s^2
speed limit = 5 m/s
position limit = 25 m

Find `s(t)`


## Speeding up

To start, I want to consider the first 3 seconds. This is when the drone goes from hovering to flying at the speed limit.

The only thing we can change is the jerk value. So to start we need to set jerk to +4 and hold it there until we reach the acceleration limit of 2 m/s^2. That happens at t = 0.5. Next we keep jerk at 0 until velocity is almost at 5 m/s (we keep it at zero for 2 seconds). Then we set jerk to -4 for 0.5 seconds. When we're done, the drone has a velocity of 5 m/s.

To find the position, we need to consider a different integral each time we changed the jerk value:
1. 0 <= t < 0.5
2. 0.5 <= t < 2.5
3. 2.5 <= t < 3

### Part 1
0 <= t < 0.5

j1(t) = 4
a1(t) = 4 * t
v1(t) = 2 * t^2
p1(t) = 2/3 * t^3

### Part 2
 0.5 <= t < 2.5

The constants matter. So I need to evaluate the previous integrals to find them.
Also t is time since part 2 started... 

j2(t) = 0
a2(t) = 2 where a1(t=0.5) = 2 = our acceleration limit (this is by design)
v2(t) = 2 * t + 0.5 where 0.5 is the constant in the integral. It equals the velocity we happen to have at t=0.5 = v1(0.5) = 0.5
p2(t) =  t^2 + 0.5*t + 0.08333 where p1(0.5) = 0.08333

We need to fix v2 and p2 so that t is time since part 1 started:

v2(t) = 2 * (t - 0.5) + 0.5
p2(t) = (t - 0.5)^2 + (t - 0.5)*t + 0.08333 

### Part 3
 2.5 <= t < 3

t is time since part 3 started...

j3(t) = -4
a3(t) = -4 * t + 2
v3(t) = -2 t^2 + 2*t + 4.5  where v2(2.5) = 4.5
p3(t) = -2/3 * t^3 + t^2 + 4.5 * t + 9.08333 where p2(2.5) = 9.08333

Now we need to adjust the equations so that t is time since part 1 started

a3(t) = -4 * (t - 2.5) + 2
v3(t) = -2 * (t - 2.5)^2 + 2 * (t - 2.5) + 4.5 
p3(t) = -2/3 * (t - 2.5)^3 + (t - 2.5)^2 + 4.5 * (t - 2.5) + 9.08333

When t = 3 we have travel 11.5 meters and we're moving at 5 meters per second.

## Steady State

This is when the drone is traveling at a constant velocity. We travel like this for 2 meters. 

3 <= t < 3.4

j(t) = 0
a(t) = 0
v(t) = 5
p(t) = 5 * t

## Slowing down

This is when the drone is slowing down. It's just like the Speeding up phase but in reverse.

3.4 <= t < 6.4 

There are 3 parts
1. 3.4 <= t < 3.9
2. 3.9 <= t < 5.9
3. 5.9 <= t < 6.4

### Part 1 

j(t) = -4

### Part 2
j(t) = 0

### Part 3
j(t) = + 4

**Comment by JaneClelandHuang** [comment]
@murphym18, rather than using fixed values for jerk, could we use the currently set values from the PID tuning (i.e., as proposed by Nate).  Is there a reason for using small values vs. reading pid-trained values?

**Comment by murphym18** [comment]
> @murphym18, rather than using fixed values for jerk, could we use the currently set values from the PID tuning (i.e., as proposed by Nate). Is there a reason for using small values vs. reading pid-trained values?

Yes, we will need to use the [MPC_JERK_AUTO](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_JERK_AUTO) parameter for jerk. That's the value that mission mode uses. By default it's 4 and that's why I chose it for my example. I created that example because I need to explore how everything works. Once I understand everything, I can create the code that animates the setpoint (by the way, what I've been calling the "Setpoint Animator" is known to the PX4 devs as a "Trajectory Generator").

Eventually, I think we'll have a function that returns another function:

```python
def mk_s(jerk, acceleration_limit, speed_limit, travel_distance):
    def s(t):
        # the trajectory generator. Returns our position along the path as a function of time.
    return s 
```

This function is pretty complicated though. So I'm putting my approach in this GitHub issue for future reference.

Also, after reading your comment, I did some more research (I was trying to find the parameters that Nate suggested) and the approach described above matches the "[jerk-limited trajectory](https://docs.px4.io/v1.11/en/config_mc/mc_jerk_limited_type_trajectory.html)" that mission mode uses. In fact, the graphs I made on my own match the ones in the docs (at least the jerk, acceleration, and velocity ones match, my position graph doesn't match because I'm considering the case where the drone starts off hovering and the PX4 docs have an initial condition where the drone is moving):

![](https://docs.px4.io/v1.11/images/jerk_limited_trajectory_1d.png)

Also, my example uses an acceleration limit that I just made up. it looks like there are parameters for setting the acceleration limits:
- [MPC_ACC_HOR](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_ACC_HOR)
- [MPC_ACC_UP_MAX](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_ACC_UP_MAX)
- [MPC_ACC_DOWN_MAX](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_ACC_DOWN_MAX)

We can set our acceleration limit to
```python
acceleration_limit = min(MPC_ACC_HOR, MPC_ACC_UP_MAX, MPC_ACC_DOWN_MAX)
```

As for the speed limit, we would pick that every time. That's just how fast we want to fly from A to B. We can pick whatever we want, but the code will probably need to cap the speed limit to the drone's top speed:

```python
drone_top_speed = min(MPC_Z_VEL_MAX_DN, MPC_Z_VEL_MAX_UP, MPC_VEL_MANUAL)
speed_limit = min(drone_top_speed, waypoint_speed)
```

Where the drone's top speed is determined by:
- [MPC_VEL_MANUAL](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_VEL_MANUAL)
- [MPC_Z_VEL_MAX_UP](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_Z_VEL_MAX_UP)
- [MPC_Z_VEL_MAX_DN](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_Z_VEL_MAX_DN)

Technically the acceleration limit and the speed limit depend on what direction we're moving. But for now, we can just pick the slowest limit.

**Comment by JaneClelandHuang** [comment]
That makes sense!  Thank you for the explanation.

**Comment by murphym18** [comment]
Found this lib that does exactly what we want:

https://github.com/pantor/ruckig

**Comment by JaneClelandHuang** [comment]
That's a really useful find!!  It will be interesting to compare what you were thinking to their solution too!

**Comment by murphym18** [comment]
I probably would have split it into cases.
1. the target is far enough that we will reach max speed 
2. the target is far enough that we will reach max acceleration
3. the target is far enough that we will reach max jerk

To figure out the boundary between each case, I would have used the 
- jerk limit
- acceleration limit
- speed limit

For example, in the example above, it takes 11.5 meters to reach max speed. So we'd use case 1 if the target is at least 23 meters away (we need 11.5 meters to speed up and 11.5 meters to slow down). Then we'd fly at a constant velocity until we reach the last 11.5 meters. Then we'd slow to reach the target.

For case 2, the acceleration limit in the example above is reached in 0.5 seconds and the drone would travel 0.08333 meters in that amount of time. So we'd use case 2 if the target is less than 23 meters but more than 2*0.08333 = 0.16666 meters away. For case two, I'd divide the distance in half. So the drone have positive acceleration for the first half and negative acceleration for the second half. I'd need to be very careful about when I introduce negative jerk. The drone would need to have zero acceleration right in the middle. That seems like a tricky detail to get correct. 

For case 3, if we were less than 16 cm, then we'd probably want to set the setpoint directly because PX4 has special PID tuning to handle a setpoint that's less than 0.5 meters away(AFAIK).

This approach is simple and pretty barebones compared to what ruckig can do. Ruckig lets us:
- specify any final position, velocity and acceleration that we want. This means we could use it to transition from hover to circle flying and have it be smoother.
-   it lets us constrain acceleration and velocity by direction. So we can limit upward acceleration to [MPC_ACC_UP_MAX](https://docs.px4.io/v1.11/en/advanced_config/parameter_reference.html#MPC_ACC_UP_MAX) for example.

Here's [a video about Ruckig](https://www.youtube.com/watch?v=b6y_3JvGFJo). Looks like this is a pretty big problem.

**Comment by murphym18** [comment]
I used Ruckig to build the example above. Here's a plot
![trajectory](https://user-images.githubusercontent.com/815081/174131117-71f05244-85eb-47af-820f-a9e027127c81.png)

Everything looks good. Where acceleration is changing, that's where jerk is either on or off. And it looks like everything is matching up as expected. At t = 3 we reach max velocity, for example

**Comment by murphym18** [comment]
Made some progress on this. Here's a video showing the box test using a Ruckig trajectory generator:

https://drive.google.com/file/d/1XWoEBa7KASI3rcqr0UFnvGqRRW-kxZgD/view?usp=sharing

So one concern is that the drone needs to _not_ stray too far away from it's path. This is because the code runs Ruckig in "offline" mode. This means that Ruckig outputs the "ideal" trajectory. And real-world conditions like wind could throw the drone's actual position off course. If this happens, the drone might get jerky and aggressive as it tries to correct it's position. The more the drone get's pushed around, the more aggressively it will try to correct itself.

**Comment by JaneClelandHuang** [comment]
That looks good.  The Iowa State group (on our NASA grant) have been working entirely with the box test and have tested different wind conditions. I could ask them to run the tests on this new hardware configuration.  In addition, I have been trying think about this problem wrt we have seen in real-world windy conditions, and I think the drones are in fact fairly aggressive in trying to keep their positions.   Their relatively aggressive flights actually help them to stay on course. I recall seeing severe yaw and roll etc in the real world when flying Ardupilot drones in high wind conditions.  All this to say -- maybe that is what we want.
